export const ROUTES_ENUM = {
  ISHOW: "/api/v1",
  ADMIN: "/admin",

  HOME: "/Home",
  AUTH: {
    BASE: "/auth",
    LOGIN: "/login",
    LOGOUT: "/logout",
    CHANGE_PASSWORD: "/change-password",
    REFRESH_TOKEN: "/refreshToken",
  },

  LOOKUP: {
    BASE: "/lookup",
    ACCOUNT: "/account",
    TAG: "/tag",
    ACTOR: "/actor",
    SECTION: "/section",
    MOVIE: "/movie",
    KIDS_MOVIE: "/kids-movie",
    SPORT_MOVIE: "/sport-movie",
    CLIP: "/clip",
    KIDS_CLIP: "/kids-clip",
    SPORT_CLIP: "/sport-clip",
    CHANNEL: "/channel",
    KIDS_CHANNEL: "/kids-channel",
    SPORT_CHANNEL: "/sport-channel",
    SERIES: "/series",
    KIDS_SERIES: "/kids-series",
    SPORT_SERIES: "/sport-series",
    TV_PROGRAMS: "/tv-program",
    KIDS_TV_PROGRAMS: "/kids-tv-program",
    SPORT_TV_PROGRAMS: "/sport-tv-program",
    CHAMPION: "/champion",
    TEAM: "/team",
  },
  ACCOUNT: {
    BASE: "/account",
    FILTER: "/list",
    CREATE: "/create",
    UPDATE: "/update",
    ACTIVATE: "/status",
    CHANGE_PASSWORD: "/change-password",
  },
  ACTOR: {
    BASE: "/actor",
    FILTER: "/list",
    CREATE: "/create",
    UPDATE: "/update",
    ACTIVATE: "/status",
  },
  CHAMPION: {
    BASE: "/champion",
    FILTER: "/list",
    CREATE: "/create",
    UPDATE: "/update",
    ACTIVATE: "/status",
  },
  COMPLAINT: {
    BASE: "/complaint",
    FILTER: "/filter",
    READ: "/status",
  },
  HELP_CENTER: {
    BASE: "/helpCenter",
    UPDATE: "/update",
  },
  TEAM: {
    BASE: "/team",
    FILTER: "/list",
    CREATE: "/create",
    UPDATE: "/update",
    ACTIVATE: "/status",
    BULK_UPLOAD: "/upload-zip"
  },
  UPCOMING_MATCH: {
    BASE: "/upcoming-match",
    FILTER: "/filter",
    CREATE: "/create",
    UPDATE: "/update",
    ACTIVATE: "/status"
  },
  CHANNEL: {
    BASE: "/channel",
    FILTER: "/list",
    CREATE: "/create",
    UPDATE: "/update",
    ACTIVATE: "/status",
    PUBLISH: "/publish",
    VIEW_SECTION_CHANNELS: "/section/list",
    ADD_CHANNEL_TO_SECTION: "/section/add",
    REMOVE_CHANNEL_FROM_SECTION: "/section/remove",
    SECTION_IS_TOP: "/section/is-top",
    VIEW_CHANNEL_SECTIONS: "/sections",
    VIEW_CHANNEL_BANNER: "/banner",
  },
  CHANNEL_EPG: {
    BASE: "/channel-epg",
    FILTER: "/list",
    CREATE: "/create",
    UPDATE: "/update",
    ACTIVATE: "/status",
    UPLOAD: "/upload/epg",
  },
  MOVIE: {
    BASE: "/movie",
    FILTER: "/filter",
    CREATE: "/create",
    UPDATE: "/update",
    PUBLISH: "/publish",
    UPDATE_TRANSCODE: "/updateTranscode",
    VIEW_SECTION_MOVIES: "/section/list",
    ADD_MOVIE_TO_SECTION: "/section/add",
    REMOVE_MOVIE_FROM_SECTION: "/section/remove",
    SECTION_IS_TOP: "/section/is-top",
    VIEW_MOVIE_SECTIONS: "/sections",
    VIEW_MOVIE_BANNER: "/banner",
  },
  MOBILE_HOME: {
    BASE: "/home",
    VIEW_SECTION_MOVIES: "/movie/section/list",
    ADD_MOVIE_TO_SECTION: "/movie/section/add",
    REMOVE_MOVIE_FROM_SECTION: "/movie/section/remove",
    MOVIE_SECTION_IS_TOP: "/movie/section/is-top",
    VIEW_SECTION_SERIES: "/series/section/list",
    ADD_SERIES_TO_SECTION: "/series/section/add",
    REMOVE_SERIES_FROM_SECTION: "/series/section/remove",
    SERIES_SECTION_IS_TOP: "/series/section/is-top",
    VIEW_SECTION_CLIP: "/clip/section/list",
    ADD_CLIP_TO_SECTION: "/clip/section/add",
    REMOVE_CLIP_FROM_SECTION: "/clip/section/remove",
    CLIP_SECTION_IS_TOP: "/clip/section/is-top",
    VIEW_SECTION_CHANNELS: "/channel/section/list",
    ADD_CHANNEL_TO_SECTION: "/channel/section/add",
    REMOVE_CHANNEL_FROM_SECTION: "/channel/section/remove",
    CHANNEL_SECTION_IS_TOP: "/channel/section/is-top",
    VIEW_SECTION_TVS: "/tv-program/section/list",
    ADD_TV_TO_SECTION: "/tv-program/section/add",
    REMOVE_TV_FROM_SECTION: "/tv-program/section/remove",
    TV_SECTION_IS_TOP: "/tv-program/section/is-top",
    VIEW_SECTIONS: "/sections",
    BANNER: "/banner",
    BANNER_LIST: "/list",
    BANNER_REMOVE: "/remove",
    MOVIE_ADD: "/movie/add",
    SERIES_ADD: "/series/add",
    CHANNEL_ADD: "/channel/add",
    TV_PROGRAM_ADD: "/tv-program/add",
    CLIP_ADD: "/clip/add",
  },
  KIDS: {
    BASE: "/kids",
    VIEW_SECTION_MOVIES: "/movie/section/list",
    ADD_MOVIE_TO_SECTION: "/movie/section/add",
    REMOVE_MOVIE_FROM_SECTION: "/movie/section/remove",
    MOVIE_SECTION_IS_TOP: "/movie/section/is-top",
    VIEW_SECTION_SERIES: "/series/section/list",
    ADD_SERIES_TO_SECTION: "/series/section/add",
    REMOVE_SERIES_FROM_SECTION: "/series/section/remove",
    SERIES_SECTION_IS_TOP: "/series/section/is-top",
    VIEW_SECTION_CLIP: "/clip/section/list",
    ADD_CLIP_TO_SECTION: "/clip/section/add",
    REMOVE_CLIP_FROM_SECTION: "/clip/section/remove",
    CLIP_SECTION_IS_TOP: "/clip/section/is-top",
    VIEW_SECTION_CHANNELS: "/channel/section/list",
    ADD_CHANNEL_TO_SECTION: "/channel/section/add",
    REMOVE_CHANNEL_FROM_SECTION: "/channel/section/remove",
    CHANNEL_SECTION_IS_TOP: "/channel/section/is-top",
    VIEW_SECTION_TVS: "/tv-program/section/list",
    ADD_TV_TO_SECTION: "/tv-program/section/add",
    REMOVE_TV_FROM_SECTION: "/tv-program/section/remove",
    TV_SECTION_IS_TOP: "/tv-program/section/is-top",
    VIEW_SECTIONS: "/sections",
    BANNER: "/banner",
    BANNER_LIST: "/list",
    BANNER_REMOVE: "/remove",
    MOVIE_ADD: "/movie/add",
    SERIES_ADD: "/series/add",
    CHANNEL_ADD: "/channel/add",
    TV_PROGRAM_ADD: "/tv-program/add",
    CLIP_ADD: "/clip/add",
  },
  SPORT: {
    BASE: "/sport",
    VIEW_SECTION_MOVIES: "/movie/section/list",
    ADD_MOVIE_TO_SECTION: "/movie/section/add",
    REMOVE_MOVIE_FROM_SECTION: "/movie/section/remove",
    MOVIE_SECTION_IS_TOP: "/movie/section/is-top",
    VIEW_SECTION_SERIES: "/series/section/list",
    ADD_SERIES_TO_SECTION: "/series/section/add",
    REMOVE_SERIES_FROM_SECTION: "/series/section/remove",
    SERIES_SECTION_IS_TOP: "/series/section/is-top",
    VIEW_SECTION_CLIP: "/clip/section/list",
    ADD_CLIP_TO_SECTION: "/clip/section/add",
    REMOVE_CLIP_FROM_SECTION: "/clip/section/remove",
    CLIP_SECTION_IS_TOP: "/clip/section/is-top",
    VIEW_SECTION_CHANNELS: "/channel/section/list",
    ADD_CHANNEL_TO_SECTION: "/channel/section/add",
    REMOVE_CHANNEL_FROM_SECTION: "/channel/section/remove",
    CHANNEL_SECTION_IS_TOP: "/channel/section/is-top",
    VIEW_SECTION_TVS: "/tv-program/section/list",
    ADD_TV_TO_SECTION: "/tv-program/section/add",
    REMOVE_TV_FROM_SECTION: "/tv-program/section/remove",
    TV_SECTION_IS_TOP: "/tv-program/section/is-top",
    VIEW_SECTIONS: "/sections"
  },
  CLIP: {
    BASE: "/clip",
    FILTER: "/filter",
    CREATE: "/create",
    UPDATE: "/update",
    PUBLISH: "/publish",
    VIEW_SECTION_CLIPS: "/section/list",
    ADD_CLIP_TO_SECTION: "/section/add",
    REMOVE_CLIP_FROM_SECTION: "/section/remove",
    SECTION_IS_TOP: "/section/is-top",
    VIEW_CLIP_SECTIONS: "/sections",
    VIEW_CLIP_BANNER: "/banner",
  },
  SERIES: {
    BASE: "/series",
    FILTER: "/filter",
    CREATE: "/create",
    UPDATE: "/update",
    PUBLISH: "/publish",
    VIEW_SERIES_SECTIONS: "/sections",
    VIEW_SERIES_BANNER: "/banner",
    VIEW_SECTION_SERIES: "/section/list",
    ADD_SERIES_TO_SECTION: "/section/add",
    REMOVE_SERIES_FROM_SECTION: "/section/remove",
    SECTION_IS_TOP: "/section/is-top",
    VIEW_SEASON_SERIES: "/season",
    VIEW_EPISODES: "/episodes",
    SERIES_PARA: "/:seriesId",
    SEASON_PARA: "/:seasonId",
    CREATE_SEASON: "/season/create",
    UPDATE_SEASON: "/season/update",
    CREATE_EPISODE: "/episode/create",
    UPDATE_EPISODE: "/episode/update",
  },
  TV_PROGRAM: {
    BASE: "/tv-program",
    FILTER: "/filter",
    CREATE: "/create",
    PUBLISH: "/publish",
    UPDATE: "/update",
    VIEW_TV_SECTIONS: "/sections",
    VIEW_SECTION_TV: "/section/list",
    ADD_TV_TO_SECTION: "/section/add",
    REMOVE_TV_FROM_SECTION: "/section/remove",
    SECTION_IS_TOP: "/section/is-top",
    VIEW_TV_BANNER: "/banner",
    VIEW_SEASON_TV: "/season",
    VIEW_EPISODES: "/episodes",
    TV_PARA: "/:tvId",
    SEASON_PARA: "/:seasonId",
    CREATE_SEASON: "/season/create",
    UPDATE_SEASON: "/season/update",
    CREATE_EPISODE: "/episode/create",
    UPDATE_EPISODE: "/episode/update",
  },
  AD: {
    BASE: "/ad",
    FILTER: "/list",
    CREATE: "/create",
    UPDATE: "/update",
    ACTIVATE: "/status",
  },
  TAG: {
    BASE: "/tag",
    FILTER: "/list",
    CREATE: "/create",
    UPDATE: "/update",
    ACTIVATE: "/status",
  },
  SECTION: {
    BASE: "/section",
    FILTER: "/list",
    CREATE: "/create",
    UPDATE: "/update",
    ACTIVATE: "/status",
    PUBLISH: "/publish",
    SECTION_NAMA_PARA: "/:sectionName",
    SECTION_ID_PARA: "/:sectionId",
  },
  STREAM: {
    BASE: "/stream",
    VIEW: "/stream/v1/poster",
    DOWNLOAD: "/download",
  },
};

export const BASE_URL = "http://localhost:8081/api/v1";

export const ERROR_MESSAGE = "FAILURE";

export const SUCCES_MESSAGE = "SUCCESS";
